obj-$(CONFIG_HID_XPADNEO) += hid-xpadneo.o
hid-xpadneo-$(CONFIG_HID_XPADNEO) += \
	consumer.o \
	core.o \
	debug.o \
	device.o \
	events.o \
	keyboard.o \
	mappings.o \
	mouse.o \
	power.o \
	quirks.o \
	rumble.o \
	synthetic.o
